
version: 2

models:
  - name: my_first_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: my_second_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: snowflake_customer_purchases
    description: "the total purchases for each customer in snowflake sample data"
    columns:
      - name: c_custkey
        tests:
          - unique
          - not_null

  - name: cumulative_sales_by_date
    description: "the cumulative sales by date based on orders table in in snowflake sample data"
    columns:
      - name: date
        tests:
          - unique
          - not_null
  - name: incremental_time

  - name: playing_with_tests
    columns:
      - name: c_custkey
        tests:
          - not_null
          - unique
    columns:
      - name: c_mktsegment
        tests:
          - accepted_values:
              values: ['BUILDING','AUTOMOBILE','MACHINERY','HOUSEHOLD','FURNITURE']
